version: '3'
services:
  app:
    build: ./
    ports:
      - "8000:8000"
      - "9000:9000"
      - "10000:10000"
    expose:
      - 8000
      - 9000
      - 10000
    volumes:
      - ./:/app
      - /app/target
      - /app/project/project
      - /app/project/target
    container_name: play-skeleton
    stdin_open: true
    tty: true
    env_file:
      - ./.env